### PR TITLE
Visual Studio 2015 project files

### PR DESCRIPTION
**Pull request by psychocrypt**
I prepared a VS2015 project without any third party dependencies.

- add VS2015 project files
- compile for all CUDA architectures
- compile without third party dependencies
- static linking against cuda 8
## Tests

- [x] build under Windows 7 with Visual Studio Community 2015

### CODE REVIEW

**Comment by fireice-uk** [comment]
Again, I don't like the idea of having potentially Microsoft's IP knocking around... Can we generate them from cmake? That would put that one to rest.

**Comment by psychocoderHPC** [comment]
Yes it is possible to generate a vc project out of cmake but on my system I always run to the point that cmake can't cant find the visual studio environment corrent.
But if a project is gernerated by VStudio it is equal to a generated one from Cmake. VStudio is only formation the xml for you.

I can try it again after the release, could we keep the pull request open? No need to merge it now.

**Comment by psychocrypt** [comment]
Yes it is possible to generate a vc project out of cmake but on my system I always run to the point that cmake can't cant find the visual studio environment corrent.
But if a project is gernerated by VStudio it is equal to a generated one from Cmake. VStudio is only formation the xml for you.

I can try it again after the release, could we keep the pull request open? No need to merge it now.

**Comment by fireice-uk** [comment]
Closing pr to delete dev. Sorry about that epic fail.

**Pull request closed without merging**
