### PR TITLE
fix missing memcpy within cuda kernel

### LINKED ISSUE #21: Another error with cuda 7.5
@psychocrypt I also get errors while building (dry system without a card)

```
fireice@LAP440:~/xmr-stak-nvidia$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17
fireice@LAP440:~/xmr-stak-nvidia$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
fireice@LAP440:~/xmr-stak-nvidia/build$ cmake -DCUDA_ARCH=50 ..
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fireice/xmr-stak-nvidia/build
fireice@LAP440:~/xmr-stak-nvidia/build$ make
[  4%] Building NVCC (Device) object CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/xmr-stak-nvidiaCuda_generated_cuda_core.cu.o
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
CMake Error at xmr-stak-nvidiaCuda_generated_cuda_core.cu.o.cmake:266 (message):
  Error generating file
  /home/fireice/xmr-stak-nvidia/build/CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/./xmr-stak-nvidiaCuda_generated_cuda_core.cu.o


CMakeFiles/xmr-stak-nvidiaCuda.dir/build.make:205: recipe for target 'CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/xmr-stak-nvidiaCuda_generated_cuda_core.cu.o' failed
make[2]: *** [CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/xmr-stak-nvidiaCuda_generated_cuda_core.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmr-stak-nvidiaCuda.dir/all' failed
make[1]: *** [CMakeFiles/xmr-stak-nvidiaCuda.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by psychocrypt**
This pull request could fix #21 

@fireice-uk could you please try if this pull request fixes the broken build on your system

### CODE REVIEW

**Comment by fireice-uk** [comment]
Still same error. Keep in mind that the stable branch builds here without problem so it will be either something about changes co .cu or somehow my hacked out cmake script doesn't break the build env any yours does :P

**Comment by psychocrypt** [comment]
I found a similar [issue here](https://github.com/BVLC/caffe/issues/4046).

**Comment by psychocrypt** [comment]
I applied a new fix, could you please test it?

Note: I can't reproduce this issue on ubuntu 14.04 with gcc 5.3 and CUDA 7.5 (hacked to support gcc>=5).  From the above linked issue in the caffe framework it is an issue with ubuntu 16.04.

**Comment by psychocrypt** [comment]
another helpful [link](http://stackoverflow.com/a/38258088) to this issue.

**Comment by psychocrypt** [comment]
> Still same error. Keep in mind that the stable branch builds here without problem so it will be either something about changes co .cu or somehow my hacked out cmake script doesn't break the build env any yours does :P

The issue was not triggered by your CMake implementation because you haven't included the PTX code for the correct compute architecture and if not manually added it build by default for `sm_20` (you should not get the best performance). You could try if the master also breaks if you add `set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS} -gencode arch=compute_50,code=sm_50)` to the `CMakeLists.txt`.

**Comment by fireice-uk** [comment]
That worked! Merging.

**Pull request merged**
