### PR TITLE
update build process in `README.md`

### PR DESCRIPTION
**Pull request by psychocrypt**
Add `make install` to the documentation to be sure tat all dependencies (config.txt) is copied to the bin folder.

I have not added the option `-DCMAKE_INSTALL_PREFIX=PATH_TO_INSTALL` to the install guide maybe it is to complicated for some users.

### CODE REVIEW

**Comment by fireice-uk** [comment]
Ok, one note. In my experience undocumented feature is worse than no feature. It annoys the users and still costs maintenance time. Maybe we should have advanced options section?

**Comment by psychocrypt** [comment]
This is a default option in CMake but yes I agree with a advanced option section. Should we add a separate file and link to or a section within the README.txt.
Should I or you begin to write the advanced guide?

**Comment by fireice-uk** [comment]
Section within readme on advanced builds will be ok. Documentation is usually better if the person that wrote the code writes it -I would have gotten even this simple one wrong... Why only `make install` anyway without `make` first?

**Comment by psychocrypt** [comment]
`make install` already includs `make`. 

```
make
make install
```
... could confuse the user. It is also possible to use `make -j install` to build in parallel mode.

**Comment by fireice-uk** [comment]
Ok. Nice to know, as long as I remember I was always doing `make` then `make install`.

**Pull request merged**
